# -*- coding: utf-8 -*-
"""lab3_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1557r2bMwKTQlC0dxJC3Sv1kFfXxEMApe
"""

from sympy import *
import matplotlib.pyplot as plt
import numpy as np

#exp5
print("Bai 5:")
##a) 
print("a) ")
x0=symbols('x')
fx=x0**2-7
c=1

fa=fx.subs(fx,c)
ll=limit(fx,x0,c,'-')
lr=limit(fx,x0,c,'+')
lx=limit(fx,x0,c)
print("Gioi han trai: {}".format(ll))
print("Gioi han phai: {}".format(lr))
print("Gioi han tai x: {}".format(lx))
if ll == lr == lx:
  print("F(x) lien tuc tai c={}".format(c))
else:
  print("F(x) Khong lien tuc tai c={}".format(c))

##b) 
print("b)")
x0=symbols('x')
fx=(2*x0-3)**(1/2)
c=2

fa=fx.subs(fx,c)
ll=limit(fx,x0,c,'-')
lr=limit(fx,x0,c,'+')
lx=limit(fx,x0,c)
print("Gioi han trai: {}".format(ll))
print("Gioi han phai: {}".format(lr))
print("Gioi han tai x: {}".format(lx))
if ll == lr == lx:
  print("F(x) lien tuc tai c={}".format(c))
else:
  print("F(x) Khong lien tuc tai c={}".format(c))

#exp 6
print("Bai 6:")
#a)
print("a)")
x0=symbols('x')
fx=(x0**2-x0-6)/(x0-3)
c=0
lx=limit(fx,x0,c)
print("Gioi han tai x: {}".format(lx))
if 5 == lx:
  print("F(x) lien tuc tai c={}".format(c))
else:
  print("F(x) Khong lien tuc tai c={}".format(c))
#b)
print("b)")
x0=symbols('x')
fx=(x0**3-8)/(x0**2-4)
c=2
lx=limit(fx,x0,c)
print("Gioi han tai x: {}".format(lx))
if 3 == lx:
  print("F(x) lien tuc tai c={}".format(c))
else:
  print("F(x) Khong lien tuc tai c={}".format(c))
c=-2
lx=limit(fx,x0,c)
print("Gioi han tai x: {}".format(lx))
if 4 == lx:
  print("F(x) lien tuc tai c={}".format(c))
else:
  print("F(x) Khong lien tuc tai c={}".format(c))

#c)
print("c)")
x0=symbols('x')
fx=(x0**2-x0-2)/(x0-2)
c=2
lx=limit(fx,x0,c)
print("Gioi han tai x: {}".format(lx))
if 1 == lx:
  print("F(x) lien tuc tai c={}".format(c))
else:
  print("F(x) Khong lien tuc tai c={}".format(c))
#d)
print("d)")
x0=symbols('x')
fx=1/x0**2
c=0
lx=limit(fx,x0,c)
print("Gioi han tai x: {}".format(lx))
if 1 == lx:
  print("F(x) lien tuc tai c={}".format(c))
else:
  print("F(x) Khong lien tuc tai c={}".format(c))
#exp 7
print("Bai 7")
#1)
print("1)")
x0=symbols('x')
fx=(x0**2-x0-2)/(x0-2)
c=2

val=fx.subs(fx,c)
lx=limit(fx,x0,c)
print("Gioi han tai x: {}".format(lx))
print("F({}): {}".format(c,val))
if val == lx:
  print("F(x) lien tuc tai c={}".format(c))
else:
  print("F(x) Khong lien tuc tai c={}".format(c))
#2)
print("2)")
x0=symbols('x')
fx=(x0**2-2*x0-3)/(2*x0-6)
c=3

val=fx.subs(fx,c)
lx=limit(fx,x0,c)
print("Gioi han tai x: {}".format(lx))
print("F({}): {}".format(c,val))
if val == lx:
  print("F(x) lien tuc tai c={}".format(c))
else:
  print("F(x) Khong lien tuc tai c={}".format(c))

#exp 8
print("Bai 8:")
#1)
x0=symbols('x')
fx=1-(1-x0**2)**(1/2)
c=-1
val=fx.subs(fx,c)
lx1=limit(fx,x0,c)
print("Gioi han tai {}: {}".format(c,lx1))
c=1
val=fx.subs(fx,c)
lx2=limit(fx,x0,c)
print("Gioi han tai {}: {}".format(c,lx2))
if lx1 == lx2:
  print("F(x) lien tuc  tren [-1,1]")
else:
  print("F(x) Khong lien tuc tren [-1,1]")

#exp 9
print("Bai 9:")
def hesogoc(x):
   hsg = (sin(10*pi/x))/(x-1)
   return print('He so goc cau PQ  tai x=',x,'la {:.1f}'.format(float(hsg)))
hesogoc(2)
hesogoc(1.5)
hesogoc(1.4)
hesogoc(1.3)
hesogoc(1.2)
hesogoc(1.1)
hesogoc(0.5)
hesogoc(0.6)
hesogoc(0.7)
hesogoc(0.8)
hesogoc(0.9)

#exp 10
print("a)")
x0=symbols('x')
fx=sin(x0)/x0
c=0
lx=limit(fx,x0,c)
print("Gioi han tai {}: {}".format(c,lx))
print("L = {}".format(lx))

print("b)")
x0=symbols('x')
fx=(x0**2+x0-6)/(x0**2-4)
c=2
lx=limit(fx,x0,c)
print("Gioi han tai {}: {}".format(c,lx))
print("L = {}".format(lx))

#lab4
#exp1
print("Lab4")
print("bai 1")
print("a)")
x0=symbols('x')
fx=4-x0**2
df=diff(fx,x0,1)
print("Dao ham cua f(x): {}".format(df))
print("b)")
x0=symbols('x')
fx=(x0-1)**2+1
df=diff(fx,x0,1)
print("Dao ham cua f(x): {}".format(df))
print("c)")
x0=symbols('t')
fx=1/x0**2
df=diff(fx,x0,1)
print("Dao ham cua f(x): {}".format(df))
print("d)")
x0=symbols('z')
fx=(1-x0)/2*x0
df=diff(fx,x0,1)
print("Dao ham cua f(x): {}".format(df))
print("e)")
x0=symbols('z')
fx=sqrt(3*x0)
df=diff(fx,x0,1)
print("Dao ham cua f(x): {}".format(df))
print("f)")
x0=symbols('z')
fx=sqrt(2*x0+1)
df=diff(fx,x0,1)
print("Dao ham cua f(x): {}".format(df))

#lab4
#exp2
print("Bai 2")
print("a)")
x0=symbols('x')
fx=x0**2-1
xa=2
ya=5
y=diff(fx,x0,1).subs(x0,xa)*(x0-xa)+ya
print("Duong tiep tuyen: {}".format(y))
val=np.arange(-10,10,0.001)
fval=lambdify(x0,fx,"numpy")(val)
yval=lambdify(x0,y,"numpy")(val)
plt.plot(val,fval,label="f(x)")
plt.plot(val,yval,label="Tiep tuyen")
plt.plot(xa,ya,'cp')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend(loc='best')
plt.show()

print("b)")
x0=symbols('x')
fx=x0-2*x0**2
xa=1
ya=-1
y=diff(fx,x0,1).subs(x0,xa)*(x0-xa)+ya
print("Duong tiep tuyen: {}".format(y))
val=np.arange(-10,10,0.001)
fval=lambdify(x0,fx,"numpy")(val)
yval=lambdify(x0,y,"numpy")(val)
plt.plot(val,fval,label="f(x)")
plt.plot(val,yval,label="Tiep tuyen")
plt.plot(xa,ya,'cp')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend(loc='best')
plt.show()

print("c)")
x0=symbols('x')
fx=x0/(x0-2)
xa=3
ya=3
y=diff(fx,x0,1).subs(x0,xa)*(x0-xa)+ya
print("Duong tiep tuyen: {}".format(y))
val=np.arange(0,4,0.003)
fval=lambdify(x0,fx,"numpy")(val)
yval=lambdify(x0,y,"numpy")(val)
plt.plot(val,fval,label="f(x)")
plt.plot(val,yval,label="Tiep tuyen")
plt.plot(xa,ya,'cp')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend(loc='best')
plt.show()

print("d)")
x0=symbols('x')
fx=8/x0**2
xa=2
ya=2
y=diff(fx,x0,1).subs(x0,xa)*(x0-xa)+ya
print("Duong tiep tuyen: {}".format(y))
val=np.arange(0.1,4,0.03)
fval=lambdify(x0,fx,"numpy")(val)
yval=lambdify(x0,y,"numpy")(val)
plt.plot(val,fval,label="g(x)")
plt.plot(val,yval,label="Tiep tuyen")
plt.plot(xa,ya,'cp')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend(loc='best')
plt.show()

print("e)")
x0=symbols('x')
fx=sqrt(x0)
xa=4
ya=2
y=diff(fx,x0,1).subs(x0,xa)*(x0-xa)+ya
print("Duong tiep tuyen: {}".format(y))
val=np.arange(0.1,10,0.03)
fval=lambdify(x0,fx,"numpy")(val)
yval=lambdify(x0,y,"numpy")(val)
plt.plot(val,fval,label="g(x)")
plt.plot(val,yval,label="Tiep tuyen")
plt.plot(xa,ya,'cp')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend(loc='best')
plt.show()

print("f)")
x0=symbols('t')
fx=x0**3+3*x0
xa=1
ya=4
y=diff(fx,x0,1).subs(x0,xa)*(x0-xa)+ya
print("Duong tiep tuyen: {}".format(y))
val=np.arange(0.1,10,0.03)
fval=lambdify(x0,fx,"numpy")(val)
yval=lambdify(x0,y,"numpy")(val)
plt.plot(val,fval,label="h(x)")
plt.plot(val,yval,label="Tiep tuyen")
plt.plot(xa,ya,'cp')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend(loc='best')
plt.show()

print("g)")
x0=symbols('x')
fx=8/sqrt(x0-2)
xa=6
ya=4
y=diff(fx,x0,1).subs(x0,xa)*(x0-xa)+ya
print("Duong tiep tuyen: {}".format(y))
val=np.arange(2.03,10,0.03)
fval=lambdify(x0,fx,"numpy")(val)
yval=lambdify(x0,y,"numpy")(val)
plt.plot(val,fval,label="f(x)")
plt.plot(val,yval,label="Tiep tuyen")
plt.plot(xa,ya,'cp')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend(loc='best')
plt.show()

print("h)")
x0=symbols('z')
fx=1+sqrt(4-x0)
xa=3
ya=2
y=diff(fx,x0,1).subs(x0,xa)*(x0-xa)+ya
print("Duong tiep tuyen: {}".format(y))
val=np.arange(-10,3.9,0.03)
fval=lambdify(x0,fx,"numpy")(val)
yval=lambdify(x0,y,"numpy")(val)
plt.plot(val,fval,label="g(x)")
plt.plot(val,yval,label="Tiep tuyen")
plt.plot(xa,ya,'cp')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend(loc='best')
plt.show()

#exp 3
print("Bai 3:")
print("a)")
x0=symbols('x')
fx=5*x0-3*x0**2
xa=1
k=diff(fx,x0,1).subs(x0,xa)
print("He so goc k: {}".format(k))

print("b)")
x0=symbols('x')
fx=1/(x0-1)
xa=3
k=diff(fx,x0,1).subs(x0,xa)
print("He so goc k: {}".format(k))

print("c)")
x0=symbols('x')
fx=x0**3-2*x0+7
xa=-2
k=diff(fx,x0,1).subs(x0,xa)
print("He so goc k: {}".format(k))


print("d)")
x0=symbols('x')
fx=(x0-1)/(x0+1)
xa=1
k=diff(fx,x0,1).subs(x0,xa)
print("He so goc k: {}".format(k))