# -*- coding: utf-8 -*-
"""lab4_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-fjVlvWA4UU7Sv-urNcAVFm2Ni_CRlpk
"""

from sympy import *
import matplotlib.pyplot as plt
import numpy as np
import math 

#lab4
#bai 4
print("Bai 4")
x0=symbols('x')
fx=-2*x0**2/3+x0
fa=(fx-fx.subs(x0,0))/(x0)
lf=limit(fa,x0,0)
print("f'(x0) = {}".format(lf))



#bai 5
print("\nBai 5")
print("\na)")
x0=symbols('x')
h=symbols('h')
fx=4-x0**2

n=-3
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))
n=0
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))
n=-1
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))

print("\nb)")
x0=symbols('x')
fx=(x0-1)**2+1
df=diff(fx,x0,1)
n=-1
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))
n=0
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))
n=2
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))

print("\nc)")
x0=symbols('x')
fx=1/x0**2
df=diff(fx,x0,1)
n=-1
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))
n=2
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))
n=sqrt(3)
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))

print("\nd)")
x0=symbols('x')
fx=(1-x0)/(2*x0)
df=diff(fx,x0,1)
n=-1
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))
n=1
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))
n=sqrt(2)
df=(fx.subs(x0,n+h)-fx.subs(x0,n))/h
lf=limit(df,h,0)
print("f'({}): {}".format(n,lf))

#Bai 6
print("\nBai6")
print("\na)")
x,z=symbols('x,z')
fx=1/(x+2)
df=(fx.subs(x,z)-fx)/(z-x)
lf=limit(df,z,x)
print("f'(x): {}".format(lf))

print("\nb)")
x,z=symbols('x,z')
fx=x**2-3*x+4
df=(fx.subs(x,z)-fx)/(z-x)
lf=limit(df,z,x)
print("f'(x): {}".format(lf))

print("\nc)")
x,z=symbols('x,z')
fx=x/(x-1)
df=(fx.subs(x,z)-fx)/(z-x)
lf=limit(df,z,x)
print("f'(x): {}".format(lf))

print("\nd)")
x,z=symbols('x,z')
fx=1+sqrt(x)
df=(fx.subs(x,z)-fx)/(z-x)
lf=limit(df,z,x)
print("f'(x): {}".format(lf))

#exp 7
print("Bai 7")

print("\na)")
x,h=symbols('x,h')
x0=0
a=[1,2,3]
fx=x**3+2*x
q=(fx.subs(x,x0+h)-fx.subs(x,x0))/h
lq = limit(q,h,0)
print("STEP 1:")
val=np.arange(x0-0.5,x0+3,0.001)
y_val=lambdify(x,fx,"numpy")(val)
plt.plot(val,y_val)
plt.show()
print("\nSTEP2:")
print("q(h): {}".format(q))

print("\nSTEP3:")
print("limit of q as h->0: {}".format(lq))
print("\nSTEP4:")
plt.plot(val,y_val)
for i in a:
  lq = limit(q,h,i)
  y=fx.subs(x,x0)+lq*(x-x0)
  y_val=lambdify(x,y,"numpy")(val)
  plt.plot(val,y_val)
plt.show()

print("\nb)")
x,h=symbols('x,h')
x0=1
a=[1,2,3]
fx=x+5/x

q=(fx.subs(x,x0+h)-fx.subs(x,x0))/h

lq = limit(q,h,0)
print("STEP 1:")
val=np.arange(x0-0.5,x0+3,0.001)
y_val=lambdify(x,fx,"numpy")(val)
plt.plot(val,y_val)
plt.show()
print("\nSTEP2:")
print("q(h): {}".format(q))

print("\nSTEP3:")
print("limit of q as h->0: {}".format(lq))
print("\nSTEP4:")
plt.plot(val,y_val)
for i in a:
  lq = limit(q,h,i)
  y=fx.subs(x,x0)+lq*(x-x0)
  y_val=lambdify(x,y,"numpy")(val)
  plt.plot(val,y_val)
plt.show()

print("\nc)")
x,h=symbols('x,h')
x0=math.pi/2
a=[1,2,3]
fx=x+sin(2*x)

q=(fx.subs(x,x0+h)-fx.subs(x,x0))/h

lq = limit(q,h,0)
print("STEP 1:")
val=np.arange(x0-0.5,x0+3,0.001)
y_val=lambdify(x,fx,"numpy")(val)
plt.plot(val,y_val)
plt.show()
print("\nSTEP2:")
print("q(h): {}".format(q))

print("\nSTEP3:")
print("limit of q as h->0: {}".format(lq))
print("\nSTEP4:")
plt.plot(val,y_val)
for i in a:
  lq = limit(q,h,i)
  y=fx.subs(x,x0)+lq*(x-x0)
  y_val=lambdify(x,y,"numpy")(val)
  plt.plot(val,y_val)
plt.show()

print("\nd)")
x,h=symbols('x,h')
x0=math.pi
a=[1,2,3]
fx=cos(x)+4*sin(2*x)

q=(fx.subs(x,x0+h)-fx.subs(x,x0))/h

lq = limit(q,h,0)
print("STEP 1:")
val=np.arange(x0-0.5,x0+3,0.001)
y_val=lambdify(x,fx,"numpy")(val)
plt.plot(val,y_val)
plt.show()
print("\nSTEP2:")
print("q(h): {}".format(q))

print("\nSTEP3:")
print("limit of q as h->0: {}".format(lq))
print("\nSTEP4:")
plt.plot(val,y_val)
for i in a:
  lq = limit(q,h,i)
  y=fx.subs(x,x0)+lq*(x-x0)
  y_val=lambdify(x,y,"numpy")(val)
  plt.plot(val,y_val)
plt.show()

#Bai8
print("\nBai 8")
x,h=symbols('x,h')
fx=x**3-3*x+1

print("\na)")
x0=3
df=(fx-fx.subs(x,x0))/(x-x0)
lf=limit(df,x,x0)
y=lf*(x-x0)+fx.subs(x,x0)
print("y={}".format(y))
val=np.arange(-10,10,0.01)
fx_val=lambdify(x,fx,"numpy")(val)
y_val=lambdify(x,y,"numpy")(val)
plt.plot(x0,fx.subs(x,x0),'ro')
plt.plot(val,fx_val)
plt.plot(val,y_val)
plt.show()

print("\nb)")
x,z=symbols('x,z')
df=diff(fx,x,1)
x0=solve(df-9,x)
plt.plot(val,fx_val)
for i in x0:
  y=df.subs(x,i)*(x-i)+fx.subs(x,i)
  print("y={}".format(y))
  y_val=lambdify(x,y,"numpy")(val)
  plt.plot(val,y_val)
  plt.plot(i,fx.subs(x,i),'ro')
plt.show()

print("c)")

yc=df*((2/3)-x)+fx+1
plt.plot(val,fx_val)
print(yc)
x0=solve(yc,x)
print(x0)
for i in x0:
  y=df.subs(x,i)*(x-i)+fx.subs(x,i)
  print("y={}".format(y))
  y_val=lambdify(x,y,"numpy")(val)
  plt.plot(val,y_val)
  plt.plot(i,fx.subs(x,i),'ro')
plt.show()

#bai9
print("Bai 9")
x=symbols('x')
fx=4*x**2-x**3
df=diff(fx,x,1)
x0=2
y0=8
val=np.arange(-2,5,0.01)
fx_val=lambdify(x,fx,"numpy")(val)
plt.plot(val,fx_val)
print("f'(x)={}".format(df))
y9=df*(x0-x)+fx-y0
s=solve(y9,x)
for i in s:
    y=df.subs(x,i)*(x-i)+fx.subs(x,i)
    print("y={}".format(y))
    y_val=lambdify(x,y,"numpy")(val)
    plt.plot(val,y_val)
    plt.plot(i,fx.subs(x,i),'ro')

x0=3
y0=9
y9=df*(x0-x)+fx-y0
s=solve(y9,x)
for i in s:
    y=df.subs(x,i)*(x-i)+fx.subs(x,i)
    print("y={}".format(y))
    y_val=lambdify(x,y,"numpy")(val)
    plt.plot(val,y_val)
    plt.plot(i,fx.subs(x,i),'ro')
plt.show()
print(s)

#bai 10
print("Bai 10")

x=symbols('x')
h=symbols('h')
print("a)")
a=1
f=(x-1)**(1/3)
fh=(f.subs(x,a+h)-f.subs(x,a))/h
lr=limit(fh,h,a,"+")
lf=limit(fh,h,a,"-")
if lr==lf:
  print("f(x) is differentiable ")
else:
  print("f(x) isn't differentiable ")

print("b)")
a=2
f=-(x+2)
fh=(f.subs(x,a+h)-f.subs(x,a))/h
lr=limit(fh,h,a,"-")
f=(x+2)
fh=(f.subs(x,a+h)-f.subs(x,a))/h
lf=limit(fh,h,a,"+")
if lr==lf:
  print("f(x) is differentiable ")
else:
  print("f(x) isn't differentiable ")

print("c)")
a=0
f=x**2
fh=(f.subs(x,a+h)-f.subs(x,a))/h
lr=limit(fh,h,a,"+")
f=0
lf=0
if lr==lf:
  print("f(x) is differentiable ")
else:
  print("f(x) isn't differentiable ")